pokete.py
pokete_classes/classes.py
pokete_data/__init__.py
pokete_data/maps.py

Outsourced all map information to maps.py and added validation.

Outsouce maps

---

pokete.py
pokete_general_use_fns.py

Added a check to warn the user when the save file has been created in a greater version than actual version of the game, to prevent data loss. I also prettified the save file using pprint.

Version checking

---

pokete_classes/effects.py

- Poketes that logically can't be affected by an effect now aren't affected by those effects anymore (Burning water Poketes)
- Burning and Poison are now less powerfull

Effect fixes

---

gen-wiki.py
wiki.md

- Sorted Poketes and attacks by type and name
- Added type headings for Poketes and attacks

Sorted wiki

---

pokete.py

Added caught_poketes to keep track of all Poketes that have EVER been in the possession of the user. This is the base to implement a Poketedex #4 upon.

Pokete dex

---

pokete.py

Added 'Evolves to ...' text in pokete dex.

added 'Evolves to ...' text in pokete dex

---

Changelog.md
README.md
gen-wiki.py
pokete.py
wiki.md

Made all needed changes for the release of v0.4.1.
First the last changes of pokete_dex have to merged.
The merge commit will later be tagged with "0.4.1" and released.

Release 0.4.1

---

pokete.py
pokete_classes/classes.py
release.py

Small changes

---

pokete.py

Added:
- Saving of maps, that already have been visited
- Highlighting of those in the minimap
- Displayed text for not visited maps is now '???'

Colored minimap

---

pokete.py

Fixed bug with money label initialization

fixed bug with money label initialization

---

assets/pics.md
gen-wiki.py
pokete.py
pokete_classes/classes.py
pokete_classes/effects.py
pokete_classes/ui_elements.py

- Added StdFrame and StdFrame2 to simplify frames and save space
- Added line breaks because auto line-wrapping in vim makes me vomit
- Made some changes to gen-wiki to make it more efficient

More small changes

---

pokete_data/attacks.py
pokete_data/poketes.py
wiki.md

Added:
- Schmetterling
- Schmetter

Added Schmetterling

---

HowToPlay.md
pokete.py
pokete_classes/classes.py

Learning Discs are items you'll be (somehow) able to find or trade in the game, that can be used to teach a special attack to a Pokete.

Learn discs

---

pokete.py
pokete_classes/classes.py
pokete_classes/ui_elements.py

Made some changes due to the Box.resize() and Frame.resize() methods in scrap_engine v0.3.3.

Scrap_engine v0.3.3

---

pokete_data/poketes.py

Added lil nut and dicko

---

pokete.py
pokete_data/mapstations.py
pokete_data/npcs.py

Added NPC.give method to simplify code.

Added NPC.give method to simplify code

---

.github/workflows/main.yml
gen-wiki.py
wiki.md

Fixed issue with table of contents and "_"s.

Fixed issue with table of contents and "_"s

---

pokete.py
pokete_data/map_data.py

Removed most exec and evals.

---

pokete.py

Added new savefile format (json) with backwards compatibility.

New savefile

---

pokete.py
pokete_data/maps.py
pokete_data/npcs.py
pokete_data/trainers.py

Fixed some dialogs/typos #50.
#48 has to be approved first.

Fix dialogs

---

gen-wiki.py
wiki.md

Fixed headings in wiki

---

.editorconfig
Pipfile
Pipfile.lock
README.md

Added some new badges to the top of the README.md:
- General additions:
- Required Python version to run this
- The license of this project
- AUR
- The votes this game has on the AUR
- The last time this game was modified on the AUR
- GitHub
- Total lines of code in this project
- How many open issues there are
- How many open pull requests there are
- What the commit activity is
- How many commits were done since last release
The `.editorconfig` file was created to have code be written the same on all contributor's devices, as it configures their editors for them.
Read more [here](https://editorconfig.org/)
`Pipfile` is a file which is **like** the `packages.json` file in JavaScript, or the `Cargo.toml` file in Rust, but a but different. It keeps track of all dependencies for this …

File additions

---

Pipfile
pokete.py

Fixed backwards compatibility.

Backwards compatibility

---

gen_wiki.py
pokete.py
pokete_classes/classes.py
pokete_data/maps.py
wiki.md

Added locations for Poketes to wiki.

Locations gen wiki

---

gen_wiki.py
pokete.py
pokete_classes/classes.py
pokete_data/maps.py
wiki.md

Added `Meadow` and `Water` class to reduce code.
Merge `locations_gen_wiki` first.

Meadow class

---

pokete.py
pokete_classes/animations.py

Added transition animation for world actions.

Fancy animations

---

pokete.py
pokete_classes/ui_elements.py

Added `BetterChooseBox`, a more beautiful alternative for `ChooseBox`.
This has no actual use as of now.

Better chooser

---

pokete_data/poketes.py
wiki.md

Added Voglus

---

pokete.py
pokete_data/poketes.py

- Added `Ratatat`
- Switched to raw strings to make pylint stop crying
- fixed capitalized `evolve_poke` names in dex

New poketes

---

pokete.py
pokete_classes/attack.py
pokete_classes/detail.py
pokete_classes/learnattack.py
pokete_classes/types.py
pokete_data/__init__.py
pokete_data/types.py

Fixed some minor issue with LDs and added an option to see the stats of a new attack when learning it.

Learning discs

---

pokete.py
pokete_classes/effects.py
pokete_classes/fightmap.py

This PR should add more logging to Pokete.

More logging

---

pokete.py
pokete_classes/fightmap.py

Method, classes and functions should be documented in detail.

More in detail documentation

---

pokete_classes/learnattack.py

Added AP label for Attack information window when learning attacks.

Added AP label for AttackInfo

---

pokete.py
pokete_classes/achievements.py
pokete_classes/fightmap.py
pokete_classes/notify.py
pokete_data/__init__.py
pokete_data/achievements.py

This PR will add achievements and the underlying notification infrastructure.

Achievements

---

Pipfile
Pipfile.lock
pokete_classes/achievements.py
pokete_classes/attack.py
pokete_classes/effects.py
pokete_classes/learnattack.py
pokete_classes/notify.py
pokete_classes/roadmap.py
pokete_classes/side_loops.py
pokete_classes/ui_elements.py

Changes due to new features in scrap_engine 1.2.0

---

pokete_classes/achievements.py
pokete_classes/attack.py
pokete_classes/effects.py
pokete_classes/learnattack.py
pokete_classes/notify.py
pokete_classes/roadmap.py
pokete_classes/ui_elements.py

This reverts commit 6957496c04bfa62951cb9b1fd722f0d513585d62.
The consequence of using se.DEFAULT_STATE was that no object was solid.

Revert "started using se.DEFAULT_STATE"

---

pokete.py
pokete_classes/achievements.py
pokete_classes/animations.py
pokete_classes/attack.py
pokete_classes/buy.py
pokete_classes/classes.py
pokete_classes/detail.py
pokete_classes/dex.py
pokete_classes/effects.py
pokete_classes/event.py
pokete_classes/fightmap.py
pokete_classes/input.py
pokete_classes/inv_items.py
pokete_classes/learnattack.py
pokete_classes/mods.py
pokete_classes/movemap.py
pokete_classes/moves.py
pokete_classes/notify.py
pokete_classes/npcs.py
pokete_classes/poke.py
pokete_classes/roadmap.py
pokete_classes/settings.py
pokete_classes/side_loops.py
pokete_classes/types.py
pokete_classes/ui_elements.py
pokete_general_use_fns.py

+ [x] `VisSetting`
+ [x] `_ev`
+ [x] `Dex`
+ [x] `Poke`
Please test this branch in depth before approving!

Code overhaul

---

pokete.py
pokete_classes/fightmap.py
pokete_data/achievements.py

Added "Catch em all" achievement.

Added "Catch em all" achievement.

---

pokete.py
pokete_classes/input.py
pokete_general_use_fns.py

Fixed wierd input behavior using `pynput` on windows.
Added `--force_pynput` option to force the game to use `pynput` as a input backend even under linux.

Fixed input

---

pokete_classes/poke.py

This fixes some attacks being reported as misses, even though they're not.

Missing attacks

---

pokete.py

Added escapecodes to collapse the game after running it.

Improved escapes

---

.gitignore
pokete.py
pokete_classes/fightmap.py

Added the option to choose another Pokete after the death of the current Pokete in a fight.

Choosing after death

---

pokete.py
pokete_classes/input.py

Added `represent_char` option to savefile so the player is able to change the their representation on the map from an `a` to something else.
Idea from [here](https://www.reddit.com/r/unixporn/comments/tk9024/comment/i1p9g3o/?utm_source=share&utm_medium=web2x&context=3)

Represent char

---

pokete.py
pokete_classes/fightmap.py
pokete_classes/landscape.py
pokete_classes/poke.py
pokete_data/items.py

Treats are items that can be gifted to you by NPCs or be found in Poketeballs and enable you to upgrade a pokete by a whole level.

Added treats

---

pokete_data/trainers.py

English spelling is dumb, I'm sorry.
FYI, I think you've misheard the idiom "best of luck" as "beste luck", which is understandable because the "of" is usually heavily reduced in pronunciation.

Fixed some typos.

---

pokete_classes/effects.py

The other part is fixed in #130
Fixes part of #138

Small grammer/spelling of #138

---

README.md

Fixed spelling mistakes, mainly with your vs you're.
Also adjusted some phrasing.
'Colour' (British and international spelling) and 'color' (American spelling) have been used once each; either is fine, but I think they should be the same as each other. I have gone with 'colour' for now.
(I've just found this project and I think it's really cool; I look forward to sitting down and playing it, but for now I wanted to show my interest by fixing some typos that I caught in the README).

fixed typos and wording

---

DevGuide.md

I just changed the broken link with correct link to my knowledge it seems to fix the problem

Broken link in for more exaple

---

pokete_classes/fightmap.py

Tried throwing myself at Issue #143.
The roll uses the speed delta clamped to 5 through 95 so even with a massive speed delta there is still a chance to either fail or succeed.

run away roll

---

mods/README.md
mods/__init__.py

Added more documentation for mods

---

pokete_classes/deck.py

- made last Pokete not freeable
- Prohibited freeing freed Poketes

Fixes to decks freeing

---

pokete.py

I noticed there was a small typo when exiting the game.

Fixed typo in the exit game popup

---

pokete_classes/fightmap.py

Fixed the game crashing by leveling up after a fight.

Fixed issue with moves

---

pokete_classes/fightmap.py
pokete_classes/ui_elements.py

Added attack infos to fight screenas requested in #179, also fixed box name disappearing after resize.

attack info box

---

pokete_classes/audio.py

@Tyson453 Please try this, it may fix the problem.

choose different settings reading

---

pokete.py
pokete_classes/achievements.py
pokete_classes/deck.py
pokete_classes/detail.py
pokete_classes/dex.py
pokete_classes/fightmap.py
pokete_classes/hotkeys.py
pokete_classes/learnattack.py
pokete_classes/movemap.py
pokete_classes/nature.py
pokete_classes/roadmap.py
pokete_classes/timer.py
pokete_classes/ui_elements.py

Made input actions savable and added input hints based on hotkey_mappings.
@magnus-ISU, I would appreciate if you took a look at this.

Made input actions savable

---

HowToPlay.md

Fixed pics in HowToPlay

---

pokete.py
pokete_classes/fightmap.py
pokete_classes/general.py
pokete_classes/npcs.py
pokete_classes/providers.py

Just slightly extended the capabilities of the provider class.

219 the fight function and the providers need a slight overhaul

---

assets/AppImageBuilder.yml

Excluded some stuff and reduced the appimage size.

Reduced appimage size

---

pokete_classes/landscape.py
pokete_classes/learnattack.py
pokete_classes/poke.py

So that wild Poketes also have learned attacks before being caught.

Added attack learning simulation for wild poketes

---

pokete.py
pokete_classes/doors.py
pokete_classes/game.py

The exception is thrown when another instance of `game()` would be called.

Added MapChangeException to reduce giant stack traces

---

pokete.py
pokete_classes/detail.py
pokete_classes/fightmap.py
pokete_classes/hotkeys.py
pokete_classes/poke.py
pokete_classes/pokestats.py
pokete_classes/providers.py

Basic statistics from feature request https://github.com/lxgr-linux/pokete/issues/239.

Introduce basic statistics

---

pokete.py
pokete_classes/audio.py
pokete_general_use_fns.py

added --no_audio option

---

pokete_classes/effects.py
pokete_classes/fightmap.py
pokete_classes/hotkeys.py
pokete_classes/poke.py

Suggestion of discussed [https://github.com/lxgr-linux/pokete/issues/246](url) feature request which consists of two toppics
Pokete name is highlighet with color of particular pokete's type. It is collision with with shiny pokete. Shiny pokete does not have color, but It's name is uppercase. If you have better suggestion, feel free to comment/implement it
Attack info box screen can be now swithed to Effect info box for attack with effect

effect info

---

pokete.py

ä, ö, ü and ß are now supported as char

Added supprot for funny german characters as char

---

pokete_classes/fightmap/inv.py

Looks like the Inv did not resize before beeing added to the fight map.
@Orest58008
Closes #259

Fixed Inventory crash

---

pokete_classes/fightmap/__init__.py

Fixed bug with fightmap not resizing on movemap resize

---

Changelog.md
release.py
wiki.md

Release v0.9.1

---

HowToPlay.md

Hello,
A colon would be better here because they are used to introduce ideas. However, a semicolon is usually in between two clauses that could stand alone as complete sentences. In this case, "catching little creatures..." is introduced as "what ten year olds do..." instead of being something that could work alone as a sentence.

Change semicolon to colon in HowToPlay.md
